# Implementing a Mathematical Equation with Tensorflow

In this exercise, we will solve the following mathematical equation
using TensorFlow:
Z=x*x*y+y+c

Mathematical equation to be solved using TensorFlow
We will use TensorFlow to solve it, as follows:

In [ ]:
import tensorflow as tf

In [ ]:
X=tf.Variable(3)
Y=tf.Variable(4)

In [ ]:
C=tf.constant(2)

In [ ]:
def myfunc(x,y,c):
    Z=x*x*y+y+c
    return Z

In [ ]:
result=myfunc(X,Y,C)
tf.print(result)

42


# Matrix Multiplication Using TensorFlow

we will use the tf.matmul() method to multiply two
matrices using tensorflow. Follow these steps to complete this
exercise:

In [ ]:
import tensorflow as tf
X=tf.Variable([[1,2,3],[4,5,6]])
Y=tf.Variable([[7,8],[9,10],[11,12]])

In [ ]:
tf.print(X)

[[1 2 3]
 [4 5 6]]


In [ ]:
tf.print(Y)

[[7 8]
 [9 10]
 [11 12]]


In [ ]:
c1=tf.matmul(X,Y)

In [ ]:
tf.print(c1)

[[58 64]
 [139 154]]


In [ ]:
c2=tf.matmul(Y,X)

In [ ]:
tf.print(c2)

[[39 54 69]
 [49 68 87]
 [59 82 105]]


# Reshaping Matrices Using the reshape()Function in TensorFlow

In [ ]:
import tensorflow as tf
A=tf.Variable([[1,2,3,4], \
[5,6,7,8], \
[9,10,11,12], \
[13,14,15,16], \
[17,18,19,20]])

In [ ]:
tf.print(A)

[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
A.shape

TensorShape([5, 4])

In [ ]:
tf.print(tf.reshape(A,[5,4,1]))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


In [ ]:
A.shape

TensorShape([5, 4])

In [ ]:
A = tf.reshape(A,[5,4,1])

In [ ]:
A.shape

TensorShape([5, 4, 1])

In [ ]:
tf.print(A)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


## Implementing the argmax() Function

In [ ]:
import tensorflow as tf
X=tf.Variable([[91,12,15], [11,88,21],[90, 87,75]])

In [ ]:
tf.print(X)

[[91 12 15]
 [11 88 21]
 [90 87 75]]


In [ ]:
X.shape

TensorShape([3, 3])

In [ ]:
tf.print(tf.argmax(X,axis=0))

[0 1 2]


Referring to the matrix in Step 2, we can see that, moving across
the columns, the index of the maximum value (91) in the first
column is 0. Similarly, the index of the maximum value along
the second column (88) is 1. And finally, the maximum value
across the third column (75) has index 2. Hence, we have the
aforementioned output.

In [ ]:
tf.print(tf.argmax(X,axis=1))

[0 1 0]


referring to the matrix in Step 2, if we move along the rows,
the maximum value along the first row is 91, which is at index 0.
Similarly, the maximum value along the second row is 88, which is at
index 1. Finally, the third row is at index 0 again, with a maximum
value of 75.

#  Exercise 5: Using an Optimizer for a Simple Linear Regression

In [ ]:
import tensorflow as tf
w=tf.Variable(0.0)
b=tf.Variable(0.0)

In [ ]:
def regression(x):
    model=w*x+b
    return model

In [ ]:
x=[1,2,3,4]
y=[0,-1,-2,-3]

In [ ]:
loss=lambda:abs(regression(x)-y)

In [ ]:
optimizer=tf.optimizers.Adam(.01)

In [ ]:
for i in range(1000):
    optimizer.minimize(loss,[w,b])

In [ ]:
# values of the w and b parameters:
tf.print(w,b)

-1.00371706 0.999803364


In [ ]:
tf.print(regression([1,2,3,4]))

[-0.00391370058 -1.00763083 -2.01134801 -3.01506495]


# Creating an ANN with TensorFlow

you will create your first sequential ANN in
TensorFlow. You will have an input layer, a hidden layer with four
units and a ReLU activation function, and an output layer with one
unit. Then, you will create some simulation data by generating
random numbers and passing it through the model, using the
model's predict method to simulate a prediction for each data
example.

In [ ]:
# Import the TensorFlow library:
import tensorflow as tf

In [ ]:
# Initialize a Keras model of the sequential class:
model = tf.keras.Sequential()

Add an input layer to the model using the
model's add method, and add the input_shape argument
with size (8,) to represent input data with eight features:

In [ ]:
model.add(tf.keras.layers.InputLayer(input_shape=(8,), \
name='Input_layer'))

Add two layers of the Dense class to the model. The first will
represent your hidden layer with four units and a ReLU activation function, and the second will represent your
output layer with one unit:

In [ ]:
model.add(tf.keras.layers.Dense(4, activation='relu',\
name='First_hidden_layer'))
model.add(tf.keras.layers.Dense(1,\
name='Output_layer'))

View the weights by calling the variables attribute of the model:

In [ ]:
model.variables

[<tf.Variable 'First_hidden_layer/kernel:0' shape=(8, 4) dtype=float32, numpy=
 array([[ 0.03206396,  0.5796501 ,  0.67258817,  0.5133162 ],
        [ 0.41188568,  0.2060104 , -0.39428276,  0.18558502],
        [-0.66977495, -0.3000161 ,  0.07169247, -0.08787888],
        [-0.46277136, -0.10706043,  0.64419717,  0.20145673],
        [ 0.6782883 , -0.5086755 , -0.3066566 , -0.66842914],
        [ 0.05493927,  0.6508911 ,  0.6191067 , -0.32602796],
        [ 0.12890965,  0.356319  , -0.45330906,  0.29798716],
        [-0.16671574,  0.54987127,  0.32530302, -0.22308749]],
       dtype=float32)>,
 <tf.Variable 'First_hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[ 0.04897773],
        [ 0.2919097 ],
        [-0.9726986 ],
        [ 0.32498205]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

This output shows all the variables that compose the model; they
include the values for all weights and biases in each layer.

In [ ]:
# Create a tensor of size 32x8, which represents a tensor with
# 32 records and 8 features:
data = tf.random.normal((32,8))

Call the predict method of the model and pass in the sample
data:

In [ ]:
model.predict(data)
# prediction

1/1 [==============================] - 0s 22ms/step


array([[ 7.1466297e-01],
       [ 4.0647754e-04],
       [ 1.9386527e-01],
       [-1.4814321e+00],
       [ 0.0000000e+00],
       [-1.0432948e+00],
       [ 9.5625764e-01],
       [-3.1454825e-01],
       [-1.7080228e+00],
       [ 4.4960856e-02],
       [ 4.4688568e-02],
       [ 8.3251648e-02],
       [ 1.5288091e-01],
       [-4.0611681e-01],
       [-1.0621691e+00],
       [-7.8553993e-01],
       [-9.2656243e-01],
       [-3.1090674e-01],
       [-5.7185799e-01],
       [ 5.5254602e-01],
       [ 2.0817879e-01],
       [ 6.1287567e-02],
       [-5.2836436e-01],
       [-2.4305741e-01],
       [ 1.5547408e-01],
       [-9.2364806e-01],
       [ 1.2650713e-02],
       [-1.0525322e+00],
       [ 4.1989010e-02],
       [-1.7544633e-01],
       [ 1.2411952e+00],
       [ 0.0000000e+00]], dtype=float32)

The output of the ANN after random inputs have been applied

Calling the predict() method on the sample data will propagate the
data through the network. In each layer, there will be a matrix
multiplication of the data with the weights, and the bias will be added
before the data is passed as input data to the next layer. This process
continues until the final output layer.

You initialized a model, added an input layer to accept data with eight

features, added a hidden layer with four units, and added an output
layer with one unit. Before fitting a model to training data, you must
first compile the model with an optimizer and choose a loss function
to minimize the value it computes by updating weights in the
training process.

# Creating a Linear Regression Model as an ANN with TensorFlow

you will create a linear regression model as an ANN
using TensorFlow. The dataset, Bias_correction_ucl.csv,
describes the bias correction of air temperature forecasts of Seoul,
South Korea. The fields represent temperature measurements of the
given date, the weather station at which the metrics were measured,
model forecasts of weather-related metrics such as humidity, and
projections for the temperature the following day. You are required
to predict the next maximum and minimum temperature given
measurements of the prior timepoints and attributes of the weather
station.

In [ ]:
# Import the TensorFlow and pandas libraries:
import tensorflow as tf
import pandas as pd

In [ ]:
df = pd.read_csv('Bias_correction_ucl.csv')

In [ ]:
# Drop the date column and drop any rows that have null
# values since your model requires numerical values only:
df.drop('Date', inplace=True, axis=1)
df.dropna(inplace=True)

Create target and feature datasets. The target dataset will
contain the columns named Next_Tmax and Next_Tmin,

while the feature dataset will contain all columns except
those named Next_Tmax and Next_Tmin:

In [ ]:
target = df[['Next_Tmax', 'Next_Tmin']]
features = df.drop(['Next_Tmax', 'Next_Tmin'],axis=1)

Rescale the feature dataset:

In [ ]:
# Rescale the feature dataset:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
feature_array = scaler.fit_transform(features)
features = pd.DataFrame(feature_array,
columns=features.columns)

In [ ]:
# Initialize a Keras model of the Sequential class:
model = tf.keras.Sequential()

Add an input layer to the model using the
model's add method, and set input_shape to be the number
of columns in the feature dataset:

In [ ]:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape[1],), \
name='Input_layer'))

Add the output layer of the Dense class to the model with a
size of 2, representing the two target variables:

In [ ]:
model.add(tf.keras.layers.Dense(2,
name='Output_layer'))

Compile the model with an RMSprop optimizer and a mean
squared error loss:

In [ ]:
model.compile(tf.optimizers.RMSprop(0.001),
loss='mse')

In [ ]:
# Add a callback for TensorBoard:
tensorboard_callback = tf.keras.callbacks\
.TensorBoard(log_dir="./logs")

In [ ]:
# Fit the model to the training data:
model.fit(x=features.to_numpy(),
y=target.to_numpy(),\
epochs=50,
callbacks=[tensorboard_callback])

Epoch 1/50
238/238 [==============================] - 1s 886us/step - loss: 625.9849
Epoch 2/50
238/238 [==============================] - 0s 887us/step - loss: 524.7980
Epoch 3/50
238/238 [==============================] - 0s 873us/step - loss: 433.2907
Epoch 4/50
238/238 [==============================] - 0s 897us/step - loss: 351.5018
Epoch 5/50
238/238 [==============================] - 0s 902us/step - loss: 279.1596
Epoch 6/50
238/238 [==============================] - 0s 911us/step - loss: 216.4005
Epoch 7/50
238/238 [==============================] - 0s 916us/step - loss: 163.3060
Epoch 8/50
238/238 [==============================] - 0s 900us/step - loss: 119.6622
Epoch 9/50
238/238 [==============================] - 0s 971us/step - loss: 85.6823
Epoch 10/50
238/238 [==============================] - 0s 895us/step - loss: 61.0546
Epoch 11/50
238/238 [==============================] - 0s 898us/step - loss: 44.2384
Epoch 12/50
238/238 [==============================] - 0s 937us/st

In [ ]:
# Evaluate the model on the training data:
loss = model.evaluate(features.to_numpy(),
target.to_numpy())
print('loss:', loss)

238/238 [==============================] - 0s 748us/step - loss: 3.5355
loss: 3.535490036010742


you have learned how to create, train, and evaluate
an ANN with TensorFlow by using Keras layers. You recreated the
linear regression algorithm by creating an ANN with an input layer
and an output layer that has one unit for each output. Here, there
were two outputs representing the maximum and minimum values of
the temperature; thus, the output layer has two units.

#Creating a Multi-Layer ANN with TensorFlow


you will create a multi-layer ANN using TensorFlow.
This model will have four hidden layers. You will add multiple layers
to the model and activation functions to the output of the layers. The
first hidden layer will have 16 units, the second will have 8 units, and
the third will have 4 units. The output layer will have 2 units.

The dataset, Bias_correction_ucl.csv, describes the bias correction of air temperature forecasts of Seoul, South Korea. The fields represent temperature measurements of the given date, the weather station at which the metrics were measured, model forecasts of weather-related metrics such as humidity, and projections for the temperature the following day. You are required to predict the next maximum and minimum temperature given measurements of the prior timepoints and attributes of the weather station.

In [ ]:
# Import the TensorFlow and pandas libraries:
import tensorflow as tf
import pandas as pd

In [ ]:
# Load in the dataset using the pandas read_csv function:
df = pd.read_csv('Bias_correction_ucl.csv')

In [ ]:
# Drop the Date column and drop any rows that have null
# values:
df.drop('Date', inplace=True, axis=1)
df.dropna(inplace=True)

In [ ]:
# Create target and feature datasets:
target = df[['Next_Tmax', 'Next_Tmin']]
features = df.drop(['Next_Tmax', 'Next_Tmin'],
axis=1)
# Rescale the feature dataset:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
feature_array = scaler.fit_transform(features)
features = pd.DataFrame(feature_array,
columns=features.columns)

In [ ]:
# Initialize a Keras model of the Sequential class:
model = tf.keras.Sequential()

In [ ]:
# Add an input layer to the model using the
# model's add method, and set input_shape to the number of
# columns in the feature dataset:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape[1],), \
name='Input_layer'))

Add three hidden layers and an output layer of
the Dense class to the model. The first hidden layer will
have 16 units, the second will have 8 units, and the third will
have 4 units. Label the layers appropriately. The output layer
will have two units to match the target variable that has two
columns:

In [ ]:
model.add(tf.keras.layers.Dense(16,
name='Dense_layer_1'))
model.add(tf.keras.layers.Dense(8,
name='Dense_layer_2'))
model.add(tf.keras.layers.Dense(4,
name='Dense_layer_3'))
model.add(tf.keras.layers.Dense(2,
name='Output_layer'))

In [ ]:
# Compile the model with an RMSprop optimizer and mean
# squared error loss:
model.compile(tf.optimizers.RMSprop(0.001),
loss='mse')

In [ ]:
# Add a callback for TensorBoard:
tensorboard_callback = tf.keras.callbacks\
.TensorBoard(log_dir="./logs")

In [ ]:
# Fit the model to the training data for 50 epochs and add a
# validation split equal to 20%:

model.fit(x=features.to_numpy(),
y=target.to_numpy(),\
epochs=50, callbacks=[tensorboard_callback], \
validation_split=0.2)

Epoch 1/50
190/190 [==============================] - 1s 3ms/step - loss: 347.1176 - val_loss: 83.8418
Epoch 2/50
190/190 [==============================] - 0s 1ms/step - loss: 22.1582 - val_loss: 7.3016
Epoch 3/50
190/190 [==============================] - 0s 1ms/step - loss: 5.6836 - val_loss: 5.5848
Epoch 4/50
190/190 [==============================] - 0s 2ms/step - loss: 4.0211 - val_loss: 4.3650
Epoch 5/50
190/190 [==============================] - 0s 1ms/step - loss: 3.2317 - val_loss: 3.7944
Epoch 6/50
190/190 [==============================] - 0s 1ms/step - loss: 2.7818 - val_loss: 3.2459
Epoch 7/50
190/190 [==============================] - 0s 1ms/step - loss: 2.5188 - val_loss: 3.0162
Epoch 8/50
190/190 [==============================] - 0s 2ms/step - loss: 2.3455 - val_loss: 2.7753
Epoch 9/50
190/190 [==============================] - 0s 1ms/step - loss: 2.2239 - val_loss: 2.8245
Epoch 10/50
190/190 [==============================] - 0s 1ms/step - loss: 2.1185 - val_loss: 2.

In [ ]:
# Evaluate the model on the training data:
loss = model.evaluate(features.to_numpy(),
target.to_numpy())
print('loss:', loss)

238/238 [==============================] - 0s 2ms/step - loss: 1.8215
loss: 1.8214621543884277


you have created an ANN with multiple hidden
layers. The loss you obtained was lower than that achieved using
linear regression, which demonstrates the power of ANNs. With some
tuning to the hyperparameters (such as varying the number of layers,
the number of units within each layer, adding activation functions,
and changing the loss and optimizer), the loss could be even lower.

# Creating a Logistic Regression Model as an ANN with TensorFlow

you will create a logistic regression model as an ANN
using TensorFlow. The dataset, qsar_androgen_receptor.csv, is
used to develop classification models for the discrimination of
binder/non-binder molecules given various attributes of the
molecules. Here, the molecule attributes represent the features of
your dataset, and their binding properties represent the target
variable, in which a positive value represents a binding molecule, and
a negative value represents a non-binding molecule. You will create a
logistic regression model to predict the binding properties of the
molecule given attributes of the molecule provided in the dataset.

In [ ]:
# Import the TensorFlow and pandas libraries:
import tensorflow as tf
import pandas as pd

In [ ]:
# Load in the dataset using the pandas read_csv function:
df = pd.read_csv('qsar_androgen_receptor.csv', \
sep=';')

In [ ]:
# Drop any rows that have null values:
df.dropna(inplace=True)

[https://towardsdatascience.com/apply-and-lambda-usage-in-pandas-b13a1ea037f7](https://) 
for apply lamda pandas 


In [ ]:
# Create target and feature datasets:
target = df['positive'].apply(lambda x: 1 if
x=='positive' else 0)
features = df.drop('positive', axis=1)

In [ ]:
# Initialize a Keras model of the Sequential class:
model = tf.keras.Sequential()

In [ ]:
# Add an input layer to the model using the
# model's add method and set input_shape to be the number
# of columns in the feature dataset:
model.add(tf.keras.layers.InputLayer\
(input_shape=(features.shape[1],), \
name='Input_layer'))

In [ ]:
# Add the output layer of the Dense class to the model with a
# size of 1, representing the target variable:

model.add(tf.keras.layers.Dense(1,
name='Output_layer', \
activation='sigmoid')
)

In [ ]:
# Compile the model with an RMSprop optimizer and binary
# cross-entropy for the loss, and compute the accuracy:

model.compile(tf.optimizers.RMSprop(0.0001), \
loss='binary_crossentropy',
metrics=['accuracy'])

In [ ]:
# Create a TensorBoard callback:

tensorboard_callback =tf.keras.callbacks.TensorBoard\
(log_dir="./logs")

In [ ]:
# Fit the model to the training data for 50 epochs, adding the
# TensorBoard callback with a validation split of 20%:

model.fit(x=features.to_numpy(), y=target.to_numpy(),\
epochs=50, callbacks=[tensorboard_callback], \
validation_split=0.2)

Epoch 1/50
43/43 [==============================] - 1s 8ms/step - loss: 0.6950 - accuracy: 0.5312 - val_loss: 0.5673 - val_accuracy: 0.8107
Epoch 2/50
43/43 [==============================] - 0s 7ms/step - loss: 0.6290 - accuracy: 0.6958 - val_loss: 0.4831 - val_accuracy: 0.8905
Epoch 3/50
43/43 [==============================] - 0s 2ms/step - loss: 0.5831 - accuracy: 0.7864 - val_loss: 0.4249 - val_accuracy: 0.9142
Epoch 4/50
43/43 [==============================] - 0s 2ms/step - loss: 0.5495 - accuracy: 0.8353 - val_loss: 0.3885 - val_accuracy: 0.9260
Epoch 5/50
43/43 [==============================] - 0s 2ms/step - loss: 0.5256 - accuracy: 0.8546 - val_loss: 0.3627 - val_accuracy: 0.9260
Epoch 6/50
43/43 [==============================] - 0s 2ms/step - loss: 0.5070 - accuracy: 0.8613 - val_loss: 0.3451 - val_accuracy: 0.9260
Epoch 7/50
43/43 [==============================] - 0s 2ms/step - loss: 0.4927 - accuracy: 0.8680 - val_loss: 0.3320 - val_accuracy: 0.9260
Epoch 8/50
43/43 [==

In [ ]:
# Evaluate the model on the training data:

loss, accuracy = model.evaluate(features.to_numpy(),
\
target.to_numpy())
print(f'loss: {loss}, accuracy: {accuracy}')

53/53 [==============================] - 0s 2ms/step - loss: 0.2782 - accuracy: 0.9098
loss: 0.2782171070575714, accuracy: 0.909845769405365


you have learned how to build a classification model
to discriminate between the binding properties of various molecules
based on their other molecular attributes. The classification model

was equivalent to a logistic regression model since it had only one
layer and was preceded by a sigmoid activation function. With only
one layer, there is a weight for each input feature and a single value
for the bias. The sigmoid activation function transforms the output of
the layer into a value between 0 and 1, which is then rounded to
represent your two classes. 0.5 and above represents one class, the
molecule with binding properties, and below 0.5 represents the other
class, molecules with non-binding properties.